# Generated by Django 5.0.4 on 2024-04-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(default='profile_pics/default_game.png', upload_to='profile_pics'),
        ),
    ]
