# Generated by Django 5.0.4 on 2024-04-24 12:58

import Gaming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0003_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='index_file',
            field=models.FileField(null=True, upload_to=Gaming.models.game_directory_path),
        ),
    ]
