# Generated by Django 5.0.4 on 2024-04-24 13:22

import Gaming.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0004_game_index_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='template_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(upload_to=Gaming.models.game_directory_path, verbose_name='APK File'),
        ),
    ]
