# Generated by Django 5.0.4 on 2024-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0005_game_template_name_alter_game_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(default='profile_pics/default_game.png', upload_to='thumbnails'),
        ),
    ]
